version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: monthly
    groups:
      node-deps:
        patterns:
          - "*"
