FROM python:3.10

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONDONTWRITEBYTECODE 1
RUN apt-get update && apt-get install -y postgresql-client pgloader
RUN apt-get clean && apt-get autoremove --purge && rm -rf /var/lib/apt/lists/*

COPY ./server /var/www/html/server
WORKDIR /var/www/html/server
RUN python3 -m pip install -r /var/www/html/server/requirements.txt --no-compile --no-cache-dir
RUN chmod +x *.sh

EXPOSE 8080
