FROM python:latest

COPY ./server /var/www/html/server
WORKDIR /var/www/html/server
RUN python3 -m pip install -r /var/www/html/server/requirements.txt
RUN python3 -m flask db upgrade
RUN python3 -c "import app; tmpapp = app.create_app(); app.models.create_first_user(tmpapp)"

EXPOSE 8080

CMD waitress-serve --call 'xss:create_app'
