"""Added tags

Revision ID: 0a7eff8e54af
Revises: 7dd0f5e2bfb9
Create Date: 2021-03-06 22:08:20.653445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7eff8e54af'
down_revision = '7dd0f5e2bfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('XSS', sa.Column('tags', sa.Text(), nullable=True))
    op.execute('UPDATE "XSS" SET tags = \'[]\'')
    op.alter_column('XSS', 'tags', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('XSS', 'tags')
    # ### end Alembic commands ###
