"""Add mfa_secret

Revision ID: 1bc9e3a8d915
Revises: af16c2b1018d
Create Date: 2022-12-17 18:50:29.973311

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1bc9e3a8d915"
down_revision = "af16c2b1018d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column("mail_to", existing_type=sa.VARCHAR(length=256), type_=sa.Text(), existing_nullable=True)

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("mail_from", existing_type=sa.VARCHAR(length=256), type_=sa.Text(), existing_nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mfa_secret", sa.String(length=32), nullable=True))

    with op.batch_alter_table("xss", schema=None) as batch_op:
        batch_op.alter_column("ip_addr", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=39), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("xss", schema=None) as batch_op:
        batch_op.alter_column("ip_addr", existing_type=sa.String(length=39), type_=sa.VARCHAR(length=15), existing_nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("mfa_secret")

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("mail_from", existing_type=sa.Text(), type_=sa.VARCHAR(length=256), existing_nullable=True)

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column("mail_to", existing_type=sa.Text(), type_=sa.VARCHAR(length=256), existing_nullable=True)

    # ### end Alembic commands ###
