"""add default mail_to

Revision ID: 5d7b14260b78
Revises: e4614ffaa6ae
Create Date: 2021-03-31 21:01:06.874925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7b14260b78'
down_revision = 'e4614ffaa6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_to', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('mail_to')

    # ### end Alembic commands ###
