"""added email

Revision ID: 83f0d8cf732e
Revises: aa16a5a6922f
Create Date: 2020-08-16 15:56:15.920690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f0d8cf732e'
down_revision = 'aa16a5a6922f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=256), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('starttls', sa.Boolean(), nullable=True),
    sa.Column('ssl_tls', sa.Boolean(), nullable=True),
    sa.Column('mail_from', sa.String(length=256), nullable=True),
    sa.Column('smtp_user', sa.String(length=128), nullable=True),
    sa.Column('smtp_pass', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('mail_to', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'mail_to')
    op.drop_table('settings')
    # ### end Alembic commands ###
