"""Add better typing

Revision ID: 8b8c263029bf
Revises: 06ce8ca0fea4
Create Date: 2025-06-22 21:11:43.727421

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b8c263029bf"
down_revision = "06ce8ca0fea4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.alter_column("key", existing_type=sa.TEXT(), type_=sa.String(length=36), existing_nullable=False)
        batch_op.alter_column("owner_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_unique_constraint(None, ["key"])

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=32), type_=sa.Text(), existing_nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(length=128), type_=sa.Text(), existing_nullable=True)

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("smtp_host", existing_type=sa.VARCHAR(length=256), type_=sa.Text(), existing_nullable=True)
        batch_op.alter_column("starttls", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("ssl_tls", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("smtp_user", existing_type=sa.VARCHAR(length=128), type_=sa.Text(), existing_nullable=True)
        batch_op.alter_column("smtp_pass", existing_type=sa.VARCHAR(length=128), type_=sa.Text(), existing_nullable=True)
        batch_op.alter_column("webhook_type", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.VARCHAR(length=128), type_=sa.Text(), existing_nullable=False)

    with op.batch_alter_table("xss", schema=None) as batch_op:
        batch_op.alter_column("xss_type", existing_type=sa.VARCHAR(length=9), nullable=False)
        batch_op.alter_column("client_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("xss", schema=None) as batch_op:
        batch_op.alter_column("client_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("xss_type", existing_type=sa.VARCHAR(length=9), nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.Text(), type_=sa.VARCHAR(length=128), existing_nullable=False)

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("webhook_type", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("smtp_pass", existing_type=sa.Text(), type_=sa.VARCHAR(length=128), existing_nullable=True)
        batch_op.alter_column("smtp_user", existing_type=sa.Text(), type_=sa.VARCHAR(length=128), existing_nullable=True)
        batch_op.alter_column("ssl_tls", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("starttls", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("smtp_host", existing_type=sa.Text(), type_=sa.VARCHAR(length=256), existing_nullable=True)

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.Text(), type_=sa.VARCHAR(length=128), existing_nullable=True)
        batch_op.alter_column("name", existing_type=sa.Text(), type_=sa.VARCHAR(length=32), existing_nullable=False)

    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column("owner_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("key", existing_type=sa.String(length=36), type_=sa.TEXT(), existing_nullable=False)

    # ### end Alembic commands ###
