"""Add webhook type

Revision ID: a994d989e1d7
Revises: 1bc9e3a8d915
Create Date: 2022-12-25 23:51:07.866989

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a994d989e1d7"
down_revision = "1bc9e3a8d915"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("webhook_type", sa.Integer(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("webhook_type")

    # ### end Alembic commands ###
