"""Models refactor

Revision ID: af16c2b1018d
Revises: 9a220b2c1ca7
Create Date: 2022-11-27 20:43:52.626964

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af16c2b1018d"
down_revision = "9a220b2c1ca7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_jti",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.drop_table("blocklist")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("starttls", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("ssl_tls", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("xss", schema=None) as batch_op:
        batch_op.alter_column("headers", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("ip_addr", existing_type=sa.VARCHAR(length=15), nullable=False)
        batch_op.alter_column("data", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("xss", schema=None) as batch_op:
        batch_op.alter_column("timestamp", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("data", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("ip_addr", existing_type=sa.VARCHAR(length=15), nullable=True)
        batch_op.alter_column("headers", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("ssl_tls", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("starttls", existing_type=sa.BOOLEAN(), nullable=True)

    op.create_table(
        "blocklist",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("jti", sa.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.drop_table("blocked_jti")
    # ### end Alembic commands ###
