"""empty message

Revision ID: b34ebe445360
Revises: fcde35e8d7d6
Create Date: 2019-05-01 22:21:32.214034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34ebe445360'
down_revision = 'fcde35e8d7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('XSS', sa.Column('local_storage', sa.TEXT(), nullable=True))
    op.add_column('XSS', sa.Column('other_data', sa.TEXT(), nullable=True))
    op.add_column('XSS', sa.Column('session_storage', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('XSS', 'session_storage')
    op.drop_column('XSS', 'other_data')
    op.drop_column('XSS', 'local_storage')
    # ### end Alembic commands ###
