"""added smtp stuff

Revision ID: bb6954d18ab3
Revises: aa16a5a6922f
Create Date: 2020-08-22 18:27:06.579100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6954d18ab3'
down_revision = 'aa16a5a6922f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=256), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('starttls', sa.Boolean(), nullable=True),
    sa.Column('ssl_tls', sa.Boolean(), nullable=True),
    sa.Column('mail_from', sa.String(length=256), nullable=True),
    sa.Column('smtp_user', sa.String(length=128), nullable=True),
    sa.Column('smtp_pass', sa.String(length=128), nullable=True),
    sa.Column('smtp_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('mail_to', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'mail_to')
    op.drop_table('settings')
    # ### end Alembic commands ###
