"""empty message

Revision ID: d0e7e8030f3c
Revises: 6360aeb9a59c
Create Date: 2025-01-19 09:49:50.846946

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0e7e8030f3c"
down_revision: Union[str, None] = "6360aeb9a59c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("blockedjti_jti_key", "blockedjti", type_="unique")
    op.create_index(op.f("ix_blockedjti_jti"), "blockedjti", ["jti"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blockedjti_jti"), table_name="blockedjti")
    op.create_unique_constraint("blockedjti_jti_key", "blockedjti", ["jti"])
    # ### end Alembic commands ###
