"""Added tags

Revision ID: f38564e35d62
Revises: 7dd0f5e2bfb9
Create Date: 2021-03-07 18:57:26.297863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f38564e35d62"
down_revision = "7dd0f5e2bfb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("XSS", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tags", sa.Text(), server_default="[]", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("XSS", schema=None) as batch_op:
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
