"""empty message

Revision ID: fcde35e8d7d6
Revises: 
Create Date: 2019-04-28 10:16:23.889164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcde35e8d7d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_login', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('XSS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referer', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=128), nullable=True),
    sa.Column('ip_addr', sa.String(length=15), nullable=True),
    sa.Column('cookies', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.TEXT(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('xss_type', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('XSS')
    op.drop_table('user')
    op.drop_table('client')
    # ### end Alembic commands ###
